services:
    marttiphpbb.usertopiccount.listener:
        class: marttiphpbb\usertopiccount\event\listener
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
            - %core.root_path%
            - %tables.posts%
            - %tables.topics%
            - %tables.users%
        tags:
            - { name: event.listener }
