services:
    marttiphpbb.usertopiccount.show_listener:
        class: marttiphpbb\usertopiccount\event\show_listener
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - %core.php_ext%
            - %core.root_path%
        tags:
            - { name: event.listener }

    marttiphpbb.usertopiccount.update_listener:
        class: marttiphpbb\usertopiccount\event\update_listener
        arguments:
            - @auth
            - @config
            - @content.visibility
            - @dbal.conn
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
            - %core.root_path%
            - %tables.posts%
            - %tables.topics%
            - %tables.users%
        tags:
            - { name: event.listener }
